import { useState } from "react";
import Head from "next/head";
import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";
import "regenerator-runtime/runtime";
import Link from "next/link";

export default function Home({ Component, pageProps }) {
  const [cid, setCid] = useState("");

  const handleSubmit = async (e) => {
    e.preventDefault(); //esto es para que recargue
    fetch("https://desafio09.herokuapp.com/api/carrito/" + cid, {
      method: "delete"
    }).catch((error) => console.log("error", error));
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form
        className="text-right border border-light p-5"
        onSubmit={handleSubmit}
      >
        <Form.Label htmlForm="id">
          Ingrese el ID del carrito as borrar:
          <input
            className="form-control"
            id="cid"
            type="text"
            onChange={(e) => setCid(e.target.value)}
          />
        </Form.Label>
        <p></p>
        <Button type="submit">Borrar</Button>
      </Form>
      <p></p>
      <Link href="/">
        <a>Volver al menú</a>
      </Link>
    </div>
  );
}
