import { useState } from "react";
import Head from "next/head";
import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";
import "regenerator-runtime/runtime";
import Link from "next/link";

export default function Home({ Component, pageProps }) {
  const [nombre, setNombre] = useState("");
  const [desc, setDesc] = useState("");
  const [cod, setCod] = useState("");
  const [foto, setFoto] = useState("");
  const [prec, setPrec] = useState("");
  const [stock, setStock] = useState("");
  const [id, setId] = useState("");
  const [cid, setCid] = useState("");

  const handleSubmit = async (e) => {
    e.preventDefault();
    const res = await fetch(
      "https://trabajofinalcoder.herokuapp.com/api/productos/" + id
    );
    const data = await res.json();
    setNombre(data.nombre);
    setDesc(data.descripcion);
    setCod(data.codigo);
    setFoto(data.foto);
    setPrec(data.precio);
    setStock(data.stock);
  };

  const delprod = async (e) => {
    e.preventDefault(); //esto es para que recargue
    fetch(
      "https://trabajofinalcoder.herokuapp.com/api/carrito/" + cid + "/productos/" + id,
      {
        method: "delete"
      }
    ).catch((error) => console.log("error", error));
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form
        className="text-right border border-light p-5"
        onSubmit={handleSubmit}
      >
        <Form.Label htmlForm="id">
          Ingrese el ID del producto a borrar:
          <input
            className="form-control"
            id="id"
            type="text"
            onChange={(e) => setId(e.target.value)}
          />
        </Form.Label>
        <p></p>
        <Form.Label htmlForm="id">
          Ingrese el ID del carrito:
          <input
            className="form-control"
            id="cid"
            type="text"
            onChange={(e) => setCid(e.target.value)}
          />
        </Form.Label>
        <p></p>
        <Form.Label htmlFor="name">
          Nombre:
          <input
            className="form-control"
            id="nombre"
            type="text"
            value={nombre}
          />
        </Form.Label>
        <p></p>
        <Form.Label htmlFor="email">
          Descripción:
          <input className="form-control" id="desc" type="text" value={desc} />
        </Form.Label>
        <p></p>
        <Form.Label htmlFor="email">
          Código:
          <input className="form-control" id="cod" type="text" value={cod} />
        </Form.Label>
        <p></p>
        <Form.Label htmlFor="email">
          Foto:
          <input className="form-control" id="foto" type="text" value={foto} />
        </Form.Label>
        <p></p>
        <Form.Label htmlFor="email">
          Precio:
          <input
            className="form-control"
            id="precio"
            type="text"
            value={prec}
          />
        </Form.Label>
        <p></p>
        <Form.Label htmlFor="email">
          Stock:
          <input
            className="form-control"
            id="stock"
            type="text"
            value={stock}
          />
        </Form.Label>
        <p></p>
        <Button type="submit">Busca</Button>
        <p></p>
        <Button onClick={delprod}>Borrar Proucto</Button>
      </Form>
      <Link href="/">
        <a>Volver al menú</a>
      </Link>
    </div>
  );
}
