import { useState } from "react";
import Head from "next/head";
import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";
import "regenerator-runtime/runtime";
import { useDispatch } from 'react-redux';
import {logtoken} from '../actions';

export default function Home({ Component, pageProps }) {
  const [username, setNombre] = useState("");
  const [password, setPass] = useState("");
  const dispatch = useDispatch();

  const handleSubmit = (e) => {
    e.preventDefault();
    //borro el prevent default para que recargue la página
    var myHeaders = new Headers();
    myHeaders.append("Content-Type", "application/json");
    var raw = JSON.stringify({
      "username": username,
      "password": password
    });
    console.log(raw)
    var requestOptions = {
      method: 'POST',
      headers: myHeaders,
      body: raw,
      redirect: 'follow'
    };
    fetch("http://localhost:8080/api/auth/login", requestOptions)
    .then(response => response.text())
    .then(result => {
      console.log(result);
      dispatch(logtoken(result))
    })
    .catch(error => console.log('error', error));
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form
        className="text-right border border-light p-5"
        onSubmit={handleSubmit}
      >
        <Form.Label htmlFor="name">
          Nombre:
          <input
            className="form-control"
            id="nombre"
            type="text"
            onChange={(e) => setNombre(e.target.value)}
          />
        </Form.Label>
        <p></p>
        <Form.Label htmlFor="email">
          Password:
          <input
            className="form-control"
            id="desc"
            type="text"
            onChange={(e) => setPass(e.target.value)}
          />
        </Form.Label>
        <p></p>
        <Button type="submit">Send</Button>
      </Form>
    </div>
  );
}
