import { useState } from "react";
import Head from "next/head";
import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";
import "regenerator-runtime/runtime";
import Link from "next/link";

export default function Home({ Component, pageProps }) {
  const [nombre, setNombre] = useState("");
  const [desc, setDesc] = useState("");
  const [cod, setCod] = useState("");
  const [foto, setFoto] = useState("");
  const [prec, setPrec] = useState("");
  const [stock, setStock] = useState("");
  const [id, setId] = useState("");

  const handleSubmit = async (e) => {
    e.preventDefault();
    const res = await fetch(
      "https://trabajofinalcoder.herokuapp.com/api/productos/" + id
    ).catch((error) => console.log("error", error));
    const data = await res.json();
    setNombre(data.nombre);
    setDesc(data.descripcion);
    setCod(data.codigo);
    setFoto(data.foto);
    setPrec(data.precio);
    setStock(data.stock);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form
        className="text-right border border-light p-5"
        onSubmit={handleSubmit}
      >
        <Form.Label htmlFor="id">
          ID a leer:
          <input
            className="form-control"
            id="id"
            type="text"
            onChange={(e) => setId(e.target.value)}
          />
        </Form.Label>
        <p></p>
        <Form.Label htmlFor="name">
          Nombre:
          <input
            className="form-control"
            id="title"
            type="text"
            value={nombre}
            readonly="readonly"
          />
        </Form.Label>
        <p></p>
        <Form.Label htmlFor="email">
          Descripción:
          <input
            className="form-control"
            id="price"
            type="text"
            value={desc}
            readonly="readonly"
          />
        </Form.Label>
        <p></p>
        <Form.Label htmlFor="email">
          Código:
          <input
            className="form-control"
            id="thumb"
            type="text"
            value={cod}
            readonly="readonly"
          />
        </Form.Label>
        <p></p>
        <Form.Label htmlFor="email">
          Foto:
          <input
            className="form-control"
            id="thumb"
            type="text"
            value={foto}
            readonly="readonly"
          />
        </Form.Label>
        <p></p>
        <Form.Label htmlFor="email">
          Precio:
          <input
            className="form-control"
            id="thumb"
            type="text"
            value={prec}
            readonly="readonly"
          />
        </Form.Label>
        <p></p>
        <Form.Label htmlFor="email">
          Stock:
          <input
            className="form-control"
            id="thumb"
            type="text"
            value={stock}
            readonly="readonly"
          />
        </Form.Label>
        <p></p>
        <Button type="submit">Leer</Button>
      </Form>
      <Link href="/">
        <a>Volver al menú</a>
      </Link>
    </div>
  );
}
