import { useState } from "react";
import Head from "next/head";
import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";
import "regenerator-runtime/runtime";
import Table from "react-bootstrap/Table";
import Link from "next/link";

export default function Readcart({ Component, pageProps }) {
  const [id, setId] = useState("");
  const [prod, setProd] = useState("");
  const handleSubmit = async (e) => {
    e.preventDefault();
    const res = await fetch(
      "https://trabajofinalcoder.herokuapp.com/api/carrito/" + id + "/productos/"
    ).catch((error) => console.log("error", error));
    const data = await res.json();
    setProd(data);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {Array.isArray(prod) ? (
        <div>
          <h1>Desafio Proyecto Final</h1>
          <Table striped bordered hover variant="dark">
            <thead>
              <tr>
                <th scope="col">Nombre</th>
                <th>Descripción</th>
                <th>Foto</th>
                <th>Precio</th>
                <th>Stock</th>
              </tr>
            </thead>
            {prod.map((prod) => (
              <tbody key={prod.id + 6}>
                <tr key={prod.id}>
                  <td key={prod.id + 1}>{prod.nombre}</td>
                  <td key={prod.id + 2}>{prod.descripcion}</td>
                  <td key={prod.id + 3}>{prod.foto}</td>
                  <td key={prod.id + 4}>{prod.precio}</td>
                  <td key={prod.id + 5}>{prod.stock}</td>
                </tr>
              </tbody>
            ))}
          </Table>
          <p></p>
        </div>
      ) : null}
      <Form
        className="text-right border border-light p-5"
        onSubmit={handleSubmit}
      >
        <Form.Label htmlFor="id">
          ID a leer:
          <input
            className="form-control"
            id="id"
            type="text"
            onChange={(e) => setId(e.target.value)}
          />
        </Form.Label>
        <p></p>
        <Button type="submit">Buscar carrito</Button>
      </Form>
      <Link href="/">
        <a>Volver al menú</a>
      </Link>
    </div>
  );
}
